Homework 3 completed
kira-vlsv/com.trello pull request #1
Opened 2021-09-14 13:54 UTC by kira-vlsv

2021-09-15 06:28 UTC, GrebNat requested changes
comments are added.
several comments should be applied for all similar class

2021-09-15 06:28 UTC, GrebNat commented on src/test/java/com/trello/ListCrudTest.java
> +        BoardApiObj.requestBuilder().buildRequest().deleteBoard(boardId);
do not delete board, which is used in another test cases. Tests should not be related

2021-09-15 06:28 UTC, GrebNat commented on src/test/java/com/trello/ListCrudTest.java
> +    public Response createNewList() {
move this method out from test class. It could be reusable

2021-09-15 06:28 UTC, GrebNat commented on src/test/java/com/trello/TrelloBoardCrudTest.java
> +        requestBuilder().buildRequest().deleteBoard(id);
entities' deleting should be done in teardown method.

2021-09-17 08:19 UTC, kira-vlsv commented on src/test/java/com/trello/ListCrudTest.java
> +        BoardApiObj.requestBuilder().buildRequest().deleteBoard(boardId);
This boars is not used in another test cases.

2021-09-17 09:25 UTC, kira-vlsv commented on src/main/java/com/trello/controllers/BoardApiObj.java
> +                .given(requestSpecification())
I didn't understand, how can I do this

2021-09-17 09:44 UTC, kira-vlsv commented on src/main/java/com/trello/constants/TrelloConstants.java
> +    public static final String KEY = "5d08d3a7d29a734f044750fccca8edbe";
I don't know how to delete it from git history

2021-09-17 10:47 UTC, GrebNat commented on src/main/java/com/trello/constants/TrelloConstants.java
> +    public static final String KEY = "5d08d3a7d29a734f044750fccca8edbe";
try it https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository

2021-10-04 10:36 UTC, GrebNat commented on src/main/java/com/trello/controllers/BoardApiObj.java
> +                .basePath(CREATE_BOARD + id)
strange 
 .basePath(String.format("%s%s", CREATE_CARD, id))

I expected smth like 
   public static final String CARD_ID_URI = "/1/cards/%s";
 .basePath(String.format(CARD_ID_URI, id))

2021-10-04 10:44 UTC, GrebNat commented on src/main/java/com/trello/controllers/BoardApiObj.java
> +                .given(requestSpecification())
this part of code is repeaded in each method. 
return given(requestSpecification())
                .basePath(

why not to have method like 
myGet(path){
return given(requestSpecification())
                .basePath(path)
                .get()
}

and reuse it in each get methods. same for the rest - put, post, delete...

2021-10-04 10:49 UTC, GrebNat commented on src/main/java/com/trello/models/AttachmentsByType.java
> +	@SerializedName("trello")
having @Getter @Setter under class is enough
also substitute equals() and toString() methods with Lombok annotations (or one annotation)

2021-10-04 10:53 UTC, GrebNat requested changes
see my comment is responses

2021-10-13 15:49 UTC, GrebNat commented on src/main/java/com/trello/controllers/ApiObj.java
> +        return baseUri;
duplication of code
have one method with property reading

2021-10-13 15:49 UTC, GrebNat commented on src/main/java/com/trello/controllers/ApiObj.java
> +        Properties property = new Properties();
move reading property to separate class

2021-10-13 15:52 UTC, GrebNat commented on src/main/java/com/trello/controllers/ListApiObj.java
> +        String path = String.format("%s%s%s", CREATE_BOARD, boardId, "/lists");
why not to have 

String.format(GET_BOARD, boardId); instead (new endpoint require )

2021-10-13 15:52 UTC, GrebNat commented on src/main/java/com/trello/models/Badges.java
> +@Setter
use @Data instead of all four

2021-10-13 15:53 UTC, GrebNat commented on src/test/java/com/trello/CardCrudTest.java
> +    private String boardDesc;
what is the reason to have class variables?

2021-10-13 15:55 UTC, GrebNat commented on src/test/java/com/trello/CardCrudTest.java
> +        boardName = "Board " + (int) (Math.random() * 100);
"Board " + (int) (Math.random() * 100);
create method with this random logic like

getRandomName("Board")

2021-11-03 07:33 UTC, kira-vlsv commented on src/test/java/com/trello/CardCrudTest.java
> +    private String boardDesc;
Because I reuse this variables in each test

2021-11-03 08:35 UTC, kira-vlsv commented on src/main/java/com/trello/controllers/ListApiObj.java
> +        String path = String.format("%s%s%s", CREATE_BOARD, boardId, "/lists");
I didn't catch what should I change

2021-11-03 11:53 UTC, GrebNat requested changes
Pls, update  all test based on made comments

2021-11-03 11:53 UTC, GrebNat commented on src/main/java/com/trello/assertions/APIAssertion.java
> +    public boolean verifyStatusCode(Response response, int httpStatus) {
No need to have this method at all, especially use in the test.
Checking, that status is 200/201 could be done once, when request is executed.

2021-11-03 11:53 UTC, GrebNat commented on src/test/java/com/trello/CardCrudTest.java
> +        apiAssertion.verifyEquals(getBoardItemAnswer(response).getName(), cardName);
verifyStatusCode - already mention about needless of this method
strange method name. and also strange overlapping the method. verifyEquals

Your aim is to create readable method names with readable error message.

good example is
apiAssertion.verifyBoardNameIsCorrect(getBoardItemAnswer(response), someBoardName)

2021-12-03 15:07 UTC, kira-vlsv commented on src/test/java/com/trello/CardCrudTest.java
> +        apiAssertion.verifyEquals(getBoardItemAnswer(response).getName(), cardName);
Hi @GrebNat,

Changes have been committed.
Please take a look.

Tnx

2022-02-02 14:54 UTC, GrebNat commented
previous comment about 200 code check ok not fully fixed

2022-02-02 14:54 UTC, GrebNat requested changes

2022-02-02 14:54 UTC, GrebNat commented on src/test/java/com/trello/ListCrudTest.java
> +        apiAssertion.verifyEquals(response.getStatusCode(), HttpStatus.SC_OK);
Initially I've asked not to verify status code is 200/201 directly in the test.
This is redundant operation, code is better to check directly when u perform http request.
In this case test will fail right away after incorrect code.

2022-02-02 14:54 UTC, GrebNat commented on src/test/java/com/trello/CardCrudTest.java
> +        response = requestBuilder().buildRequest().getCard(id);
// create card
        response = createNewCard(idList, cardName, cardDesc);
        id = getCardItemAnswer(response).getId();

        // verify that card created
        response = requestBuilder().buildRequest().getCard(id);

there is a mismatch here with calling post request for creation and get request for read. 
why requestBuilder().buildRequest() ??

2022-02-02 14:54 UTC, GrebNat commented on src/test/java/com/trello/CardCrudTest.java
> +        apiAssertion.verifyEquals(response.getStatusCode(), HttpStatus.SC_NOT_FOUND);
404 code verification is ok here

2022-02-24 11:46 UTC, merged